### ISSUE TITLE
Clarify JSON-only Support for Chat Import Feature

### ISSUE THREAD

**Issue by StaticAccess** [StaticAccess/Lynai#5]
![Screenshot 2024-10-27 171012](https://github.com/user-attachments/assets/b40356b0-495f-4cde-ad00-b6925a365a46)

## Description
Currently, our chat room's import feature only supports JSON data, but this limitation is not clearly communicated to the end user. We need to update the UI and user messaging to make this restriction clear and prevent confusion.

## Current Status
- The chat import feature only accepts JSON files
- Users are not explicitly informed about this limitation before attempting to import
- The error message when a non-JSON file is selected is generic

## Objectives
- Clearly communicate to users that only JSON files are supported for chat import
- Prevent users from attempting to upload non-JSON files
- Provide clear guidance on the expected file format

## Tasks
- [ ] Update the import dialog UI:
  - [ ] Change the button text from "Import Chat" to "Import Chat (JSON only)"
  - [ ] Add an informational text below the file input explaining the JSON requirement
- [ ] Modify the file input to only accept .json files:
  ```typescript:FrontEnd/app/chat-room/[roomId]/page.tsx
  <Input
    type="file"
    accept=".json"
    onChange={handleImportChat}
    ref={fileInputRef}
  />
  ```
- [ ] Update the "Choose JSON File" button text to reinforce the JSON requirement:
  ```typescript:FrontEnd/app/chat-room/[roomId]/page.tsx
  <Button onClick={() => fileInputRef.current?.click()}>
    Choose JSON File
  </Button>
  ```
- [ ] Enhance the error toast message for non-JSON file attempts:
  ```typescript:FrontEnd/app/chat-room/[roomId]/page.tsx
  toast({
    title: "Invalid File Type",
    description: "Only JSON files are supported for chat import. Please select a .json file.",
    variant: "destructive",
  });
  ```
- [ ] Add a help icon or link near the import option that explains the required JSON format
- [ ] Update any relevant documentation or help sections to mention the JSON-only import feature

## Acceptance Criteria
1. The import dialog clearly states that only JSON files are supported
2. The file input is restricted to only accept .json files
3. Attempting to import a non-JSON file results in a clear, specific error message
4. Users have access to information about the required JSON format for import

## Additional Notes
- Consider providing a sample JSON file structure in the documentation
- Explore the possibility of adding support for other common chat export formats in the future

## Resources
- [Current chat room component code](link-to-current-code-file)
- [JSON file format specification](https://www.json.org/json-en.html)

## Estimated Time
4-6 hours

## Assigned To
@frontend-developer

## Labels
frontend, ux-improvement, documentation, high-priority
