### ISSUE TITLE
Enhance UI for Download and Import Buttons in Chat Room

### ISSUE THREAD

**Issue by StaticAccess** [StaticAccess/Lynai#6]
![Screenshot 2024-10-27 171724](https://github.com/user-attachments/assets/b86eaf9a-8d9f-4793-9d4c-8af5001079e3)

## Description
The current UI for the download and import functionality in our chat room needs improvement. The buttons are small and potentially difficult to use, especially on mobile devices. We need to enhance the user experience by making these features more prominent and user-friendly.

## Current Status
- Download and import options are hidden behind a small popover button
- The buttons are not easily discoverable
- The UI is not optimized for mobile devices
- The functionality is not immediately clear to users

## Objectives
- Improve the visibility and usability of download and import features
- Make the UI more intuitive and mobile-friendly
- Provide clear visual cues for these important functions

## Tasks
- [ ] Redesign the download and import section:
  - [ ] Move these options out of the popover into the main UI
  - [ ] Create larger, more prominent buttons for download and import
- [ ] Update the button layout in the chat room footer:
  ```typescript:FrontEnd/app/chat-room/[roomId]/page.tsx
  <CardFooter className="border-t p-4">
    <div className="w-full space-y-4">
      <div className="flex flex-wrap justify-between items-center gap-2">
        {/* Existing time limit selector */}
        <div className="flex items-center space-x-2">
          <Button onClick={() => handleDownloadChat('txt')} variant="outline">
            <Download className="mr-2 h-4 w-4" />
            Download TXT
          </Button>
          <Button onClick={() => handleDownloadChat('json')} variant="outline">
            <Download className="mr-2 h-4 w-4" />
            Download JSON
          </Button>
          <Button onClick={() => setIsImportDialogOpen(true)} variant="outline">
            <Upload className="mr-2 h-4 w-4" />
            Import Chat
          </Button>
        </div>
      </div>
      {/* Existing message input form */}
    </div>
  </CardFooter>
  ```
- [ ] Add tooltips to the buttons for additional clarity:
  ```typescript:FrontEnd/app/chat-room/[roomId]/page.tsx
  import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip"

  // Inside the component:
  <Tooltip>
    <TooltipTrigger asChild>
      <Button onClick={() => handleDownloadChat('txt')} variant="outline">
        <Download className="mr-2 h-4 w-4" />
        Download TXT
      </Button>
    </TooltipTrigger>
    <TooltipContent>
      <p>Download chat as plain text</p>
    </TooltipContent>
  </Tooltip>
  ```
- [ ] Implement responsive design for mobile devices:
  - [ ] Use a grid or flex layout to stack buttons vertically on smaller screens
  - [ ] Adjust button sizes and padding for better touch targets
- [ ] Add visual feedback for button interactions (hover, active states)
- [ ] Consider adding icons to buttons for better visual representation
- [ ] Ensure proper contrast and accessibility for all UI elements

## Acceptance Criteria
1. Download and import buttons are clearly visible in the main chat room UI
2. Buttons are large enough for comfortable use on both desktop and mobile devices
3. Tooltips provide additional context for each button's functionality
4. UI is responsive and looks good on various screen sizes
5. Buttons provide clear visual feedback on interaction
6. The new design maintains consistency with the overall app aesthetic

## Additional Notes
- Consider A/B testing the new design with a small group of users
- Explore the possibility of adding a "quick action" floating button for mobile that expands to show download/import options

## Resources
- [Current chat room component code](link-to-current-code-file)
- [Shadcn UI Components](https://ui.shadcn.com/)

## Estimated Time
8-12 hours

## Assigned To
@frontend-developer

## Labels
frontend, ui-improvement, ux-enhancement, mobile-friendly, medium-priority
